-- MySQL Script generated by MySQL Workbench
-- Mon Mar 22 01:06:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema logipeet
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema logipeet
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `logipeet` DEFAULT CHARACTER SET utf8 ;
USE `logipeet` ;

-- -----------------------------------------------------
-- Table `logipeet`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logipeet`.`User` (
  `idUser` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `age` INT NULL,
  `gender` INT NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `type_user` INT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logipeet`.`Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logipeet`.`Events` (
  `idEvents` INT NOT NULL,
  `event_init` DATETIME NULL,
  `event_fin` DATETIME NULL,
  `event_type` INT NULL,
  `event_name` VARCHAR(45) NULL,
  PRIMARY KEY (`idEvents`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logipeet`.`Cannil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logipeet`.`Cannil` (
  `idCannil` INT NOT NULL AUTO_INCREMENT,
  `name_cannil` VARCHAR(45) NULL,
  `adress_cannil` VARCHAR(45) NULL,
  `coordinates_cannil` VARCHAR(45) NULL,
  PRIMARY KEY (`idCannil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logipeet`.`Storage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logipeet`.`Storage` (
  `idStorage` INT NOT NULL AUTO_INCREMENT,
  `name_product` VARCHAR(45) NULL,
  `code_product` VARCHAR(45) NULL,
  `weight` VARCHAR(45) NULL,
  `amount` INT NULL,
  `Cannil_idCannil` INT NOT NULL,
  PRIMARY KEY (`idStorage`),
  INDEX `fk_Storage_Cannil1_idx` (`Cannil_idCannil` ASC) VISIBLE,
  CONSTRAINT `fk_Storage_Cannil1`
    FOREIGN KEY (`Cannil_idCannil`)
    REFERENCES `logipeet`.`Cannil` (`idCannil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logipeet`.`Login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logipeet`.`Login` (
  `id_inout_c` INT NOT NULL AUTO_INCREMENT,
  `time_in_c` DATETIME NULL,
  `time_out_c` DATETIME NULL,
  `Cannil_idCannil` INT NOT NULL,
  `User_idUser` INT NOT NULL,
  PRIMARY KEY (`id_inout_c`),
  INDEX `fk_Login_Cannil1_idx` (`Cannil_idCannil` ASC) VISIBLE,
  INDEX `fk_Login_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_Login_Cannil1`
    FOREIGN KEY (`Cannil_idCannil`)
    REFERENCES `logipeet`.`Cannil` (`idCannil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Login_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `logipeet`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logipeet`.`Animals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logipeet`.`Animals` (
  `idAnimals` INT NOT NULL AUTO_INCREMENT,
  `name_animal` VARCHAR(45) NULL,
  `history_animal` VARCHAR(45) NULL,
  `photo_animal` VARCHAR(45) NULL,
  `race_animal` VARCHAR(45) NULL,
  `Cannil_idCannil` INT NOT NULL,
  PRIMARY KEY (`idAnimals`),
  INDEX `fk_Animals_Cannil1_idx` (`Cannil_idCannil` ASC) VISIBLE,
  CONSTRAINT `fk_Animals_Cannil1`
    FOREIGN KEY (`Cannil_idCannil`)
    REFERENCES `logipeet`.`Cannil` (`idCannil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logipeet`.`Sensors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logipeet`.`Sensors` (
  `idSensors` INT NOT NULL AUTO_INCREMENT,
  `type_sensor` VARCHAR(45) NULL,
  `serial_number` INT NULL,
  `satus_sen` VARCHAR(45) NULL,
  `log_sens` VARCHAR(45) NULL,
  `Cannil_idCannil` INT NOT NULL,
  PRIMARY KEY (`idSensors`),
  INDEX `fk_Sensors_Cannil1_idx` (`Cannil_idCannil` ASC) VISIBLE,
  CONSTRAINT `fk_Sensors_Cannil1`
    FOREIGN KEY (`Cannil_idCannil`)
    REFERENCES `logipeet`.`Cannil` (`idCannil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logipeet`.`User_has_Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logipeet`.`User_has_Events` (
  `User_idUser` INT NOT NULL,
  `Events_idEvents` INT NOT NULL,
  PRIMARY KEY (`User_idUser`, `Events_idEvents`),
  INDEX `fk_User_has_Events_Events1_idx` (`Events_idEvents` ASC) VISIBLE,
  INDEX `fk_User_has_Events_User1_idx` (`User_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_User_has_Events_User1`
    FOREIGN KEY (`User_idUser`)
    REFERENCES `logipeet`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Events_Events1`
    FOREIGN KEY (`Events_idEvents`)
    REFERENCES `logipeet`.`Events` (`idEvents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
