"""empty message

Revision ID: 1ec275540c1d
Revises: 
Create Date: 2021-04-13 23:10:30.201321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ec275540c1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_init', sa.String(length=64), nullable=True),
    sa.Column('event_out', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=True)
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.Integer(), nullable=True),
    sa.Column('inst_time', sa.DateTime(), nullable=True),
    sa.Column('amount_food', sa.Integer(), nullable=True),
    sa.Column('amount_water', sa.Integer(), nullable=True),
    sa.Column('battery', sa.Integer(), nullable=True),
    sa.Column('last_sup', sa.DateTime(), nullable=True),
    sa.Column('status_sens', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_id'), 'sensors', ['id'], unique=True)
    op.create_table('storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_product', sa.String(length=45), nullable=False),
    sa.Column('code_product', sa.String(length=45), nullable=False),
    sa.Column('weight', sa.String(length=45), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_id'), 'storage', ['id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=9), nullable=True),
    sa.Column('type_user', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_storage_id'), table_name='storage')
    op.drop_table('storage')
    op.drop_index(op.f('ix_sensors_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
