"""empty message

Revision ID: 459cfdfe9195
Revises: 1ec275540c1d
Create Date: 2021-04-13 23:40:17.095683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459cfdfe9195'
down_revision = '1ec275540c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cannil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_cannil', sa.String(length=45), nullable=True),
    sa.Column('adress_cannil', sa.String(length=45), nullable=True),
    sa.Column('coordinates_cannil', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cannil_id'), 'cannil', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cannil_id'), table_name='cannil')
    op.drop_table('cannil')
    # ### end Alembic commands ###
