"""empty message

Revision ID: 669457dd6cdf
Revises: 
Create Date: 2021-06-25 08:06:20.834216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669457dd6cdf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_animal', sa.String(length=45), nullable=True),
    sa.Column('history_animal', sa.String(length=45), nullable=True),
    sa.Column('photo_animal', sa.String(length=45), nullable=True),
    sa.Column('race_animal', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_id'), 'animals', ['id'], unique=True)
    op.create_table('cannil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_cannil', sa.String(length=45), nullable=True),
    sa.Column('adress_cannil', sa.String(length=45), nullable=True),
    sa.Column('coordinates_cannil', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cannil_id'), 'cannil', ['id'], unique=True)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_init', sa.String(length=64), nullable=True),
    sa.Column('event_out', sa.String(length=64), nullable=True),
    sa.Column('event_type', sa.Integer(), nullable=True),
    sa.Column('event_name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=True)
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial_number', sa.Integer(), nullable=True),
    sa.Column('inst_time', sa.DateTime(), nullable=True),
    sa.Column('amount_food', sa.Integer(), nullable=True),
    sa.Column('amount_water', sa.Integer(), nullable=True),
    sa.Column('battery', sa.Integer(), nullable=True),
    sa.Column('last_sup', sa.DateTime(), nullable=True),
    sa.Column('status_sens', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_id'), 'sensors', ['id'], unique=True)
    op.create_table('storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_product', sa.String(length=45), nullable=False),
    sa.Column('code_product', sa.String(length=45), nullable=False),
    sa.Column('weight', sa.String(length=45), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_id'), 'storage', ['id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('type_user', sa.Boolean(), nullable=True),
    sa.Column('active_user', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_storage_id'), table_name='storage')
    op.drop_table('storage')
    op.drop_index(op.f('ix_sensors_id'), table_name='sensors')
    op.drop_table('sensors')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_cannil_id'), table_name='cannil')
    op.drop_table('cannil')
    op.drop_index(op.f('ix_animals_id'), table_name='animals')
    op.drop_table('animals')
    # ### end Alembic commands ###
