"""empty message

Revision ID: b3a955e7f5cd
Revises: 459cfdfe9195
Create Date: 2021-04-13 23:53:10.369502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3a955e7f5cd'
down_revision = '459cfdfe9195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_animal', sa.String(length=45), nullable=True),
    sa.Column('histoy_animal', sa.String(length=45), nullable=True),
    sa.Column('photo_animal', sa.String(length=45), nullable=True),
    sa.Column('race_animal', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_id'), 'animals', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_animals_id'), table_name='animals')
    op.drop_table('animals')
    # ### end Alembic commands ###
