"""empty message

Revision ID: cbc9f8338f67
Revises: 681c47e34337
Create Date: 2021-04-14 07:06:24.819305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbc9f8338f67'
down_revision = '681c47e34337'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('history_animal', sa.String(length=45), nullable=True))
    op.drop_column('animals', 'histoy_animal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('histoy_animal', mysql.VARCHAR(length=45), nullable=True))
    op.drop_column('animals', 'history_animal')
    # ### end Alembic commands ###
