"""empty message

Revision ID: e47462c2a65c
Revises: 
Create Date: 2021-04-07 08:03:50.201240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47462c2a65c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('idUser', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=9), nullable=True),
    sa.Column('type_user', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('idUser'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_idUser'), 'users', ['idUser'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_idUser'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
